#!/bin/bash
#import config file
source ~/.config/eww/vertical_bar/vertical_bar.conf

#Counts number of windows on each workspace (1-10) -> {"Workspace ID": Number of Windows} -JSON
count_windows (){
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: [.windows, .lastwindowtitle]}) | from_entries')
    seq 1 $WORKSPACES_DISPLAYED | jq --argjson windows "${WORKSPACE_WINDOWS}" -s -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//[0, ""])})'
}

socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	count_windows
done
