#!/bin/bash

## Get Volume
get_vol() {
	while true; do
        wpctl get-volume @DEFAULT_SINK@ | sed 's/[^0-9]*//g'  | sed 's/^0//'
	sleep 1
	done
}

## Set Volume
set_vol() {
  wpctl set-volume @DEFAULT_SINK@ $1%
}

## Toggle Volume
toggle_vol() {
  wpctl set-mute @DEFAULT_SINK@ toggle
}


#concentrate here
## Get Volume Icon
get_volicon() {
  	MUTE="$(pactl get-sink-mute @DEFAULT_SINK@)"
  	if [[ "$MUTE" == "Mute: no" ]]; then
        echo "🔉"
  	else
        echo "🔇"
  	fi
}

## Get Mic Icon
get_micicon() {
  	MUTE="$(pactl get-source-mute @DEFAULT_SOURCE@)"
  	if [[ "$MUTE" == "Mute: no" ]]; then
        echo ""
  	else
    	echo ""
  	fi
}

## Toggle Mic
toggle_mic() {
  wpctl set-mute @DEFAULT_SOURCE@ toggle
}

## Get Mic
get_mic() {
	while true; do
    wpctl get-volume @DEFAULT_SOURCE@ | sed 's/[^0-9]*//g'  | sed 's/^0//'
		sleep 1
	done
}

## Set Mic
set_mic() {
  wpctl set-volume @DEFAULT_SOURCE@ $1%
}




if [[ "$1" == "--set-vol" ]]; then
	set_vol "$2"
elif [[ "$1" == "--get-vol" ]]; then
	get_vol
elif [[ "$1" == "--toggle-vol" ]]; then
	toggle_vol
elif [[ "$1" == "--get-volicon" ]]; then
	get_volicon
elif [[ "$1" == "--get-micicon" ]]; then
	get_micicon
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--get-mic" ]]; then
	get_mic
elif [[ "$1" == "--set-mic" ]]; then
	set_mic "$2"
fi
