#!/bin/bash

spaces (){
    #Lists how many windows are open on each workspaces -> "Workspace ID": Number of Windows,
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    #Reformats the output to [{"id":"1", "windows":x},{"id":"2", "windows":x},...] for all workspaces (1->10)
	seq 1 10 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
