#!/bin/sh
eww="eww -c $HOME/.config/eww/bar"

if [ "$1" == "--calendar" ];then
  $eww close calendar || (\
      $eww update day="`scripts/time_info --day`"; \
      $eww update month="`scripts/time_info --month`"; \
      $eww update year="`scripts/time_info --year`"; \
      $eww open calendar) 

elif [ "$1" == "--power-manager" ];then
  X_COR=$(python ~/.config/eww/bar/scripts/get_positions.py --battery_coordinates)
  $eww close powerManager || (\
      $eww open powerManager --arg x_cor=$X_COR) 

elif [ "$1" == "--main-bar" ];then
  WIDTH=$(python ~/.config/eww/bar/scripts/get_positions.py --main_bar_width)
  $eww close bar || (\
      $eww open bar --screen 0 --arg width=$WIDTH) 
fi
